### ISSUE TITLE
AustralianPayroll.Timesheets.Where doesn't appear to work

### ISSUE THREAD

**Issue by Clam-** [XeroAPI/Xero-Net#151]
Attempting to do AustralianPayroll().Timesheets.Where("StartDate > 0") for example returns:
```
An exception of type 'System.Runtime.Serialization.SerializationException' occurred in Xero.Api.dll but was not handled in user code

Additional information: Type definitions should start with a '{', expecting serialized type 'ApiException', got string starting with: <Response xmlns:i="http://www.w3.org/2001/XMLSchem
```

AustralianPayroll().Timesheets.Find() returns Timesheets as expected.

Any advice would be appreciated. Thanks.

**Comment by MJMortimer** [comment]
Hey Clam,

The issue is how the .Where is being used. StartDate is a DateTime property. StartDate > 0 doesn't make sense because you cannot compare DateTime with int. In the parsing of the filter is where the exception is originating.

This will work however, 
AustralianPayroll().TimeSheets.Where("StartDate < DateTime.Parse(\"2015-12-18\")").Find();

That would find all TimeSheets with start dates earlier than 2015-12-18.

In the future, these types of questions are best directed to our [Community Forums](https://community.xero.com/developer/), so if you have any more questions on the usage of this wrapper or Xero's API in general, feel free to raise a discussion there.

Cheers,
Matt

**Comment by Clam-** [comment]
Hello,

Thank you for the informative reply. I really appreciate it.
Sorry for the mix-up and I'll be sure to direct any similar queries to the Community Forums.

**Comment by MJMortimer** [comment]
No worries, happy to help :)
