### ISSUE TITLE
Azure Web Apps

### ISSUE THREAD

**Issue by jachin84** [XeroAPI/Xero-Net#220]
I have a partner application that I am attempting to deploy to Microsoft Azure; specifically Azure Apps Services. Please note that Azure Apps Services is not Azure Cloud Services, they are different things. See https://azure.microsoft.com/en-us/services/app-service/web/ for reference.

Azure App Services does not allow importing custom root certificates. As a result there is no way to import the Entrust Certificate for client authentication. 

Is there any way around this? Microsoft support have suggested using client certificates that chain back to a certificate already trusted by Azure. Is this an option?

**Comment by MatthewSteeples** [comment]
https://social.msdn.microsoft.com/Forums/en-US/c9e17417-e50d-4eff-9676-7d76db33264c/certificate-chain-not-being-imported-to-azure-website?forum=windowsazurewebsitespreview

We've been trying to find a way to get this to work too. Our best bet is probably getting Xero to convince Microsoft to add the root cert as trusted. Letsencrypt managed it recently but I wouldn't hold your breath.

Our workaround is to use Cloud Services rather than Web Apps

**Comment by AllenDigital** [comment]
I believe that when pull request 233 makes its way in it should fix the issue. Web Apps has never liked the entrust cert and 233 removes this requirement for partner apps.

**Comment by MatthewSteeples** [comment]
Can confirm this now works in Azure App service if you reconfigure the endpoint that your app talks to (don't need to wait for #233 to land).

**Comment by AllenDigital** [comment]
Very smooth upgrade to use Azure Apps with 233 landed.

**Comment by MJMortimer** [comment]
This is excellent news! 
Thanks for the confirmation @MatthewSteeples and @AllenDigital
