### ISSUE TITLE
Impossible to get response DateTimeUTC from API calls

### ISSUE THREAD

**Issue by davidhusselmann** [XeroAPI/Xero-Net#240]
Using the old wrapper library I was able to obtain the Xero server/database timestamp.  It seems it is impossible to do this with Xero-Net.

The reason I use this is to get around clock drift when you're doing multiple calls using the ModifiedSince filter.  I don't want to miss an invoice by milliseconds if our client clock drifts (or is out by hours  -- who knows).

The value is still being returned from the API; here is a Fiddler grab:

HTTP/1.1 200 OK

```
  {
  "Id": "73...31",
  "Status": "OK",
  "ProviderName": "DotGolf",
  "DateTimeUTC": "\/Date(1485297707246)\/",    <------
  "Invoices": [
    {
      "Type": "ACCREC",
```

Yes, it's in ugly /Date(...)/ format, but it's still a timestamp.

Is it possible to expose this value via the SDK?

**Comment by MatthewSteeples** [comment]
As a workaround, the way that we do this is to use the highest modified time of the type of entity we're pulling back, then it doesn't matter what your own local clock says.

**Comment by MJMortimer** [comment]
This wrapper works on datacontracts defined at the level below (The enumeration of Invoices/Contacts etc) the ApiResponse that contains this information. Changing the to expose the entire API response metadata as well would enforce a breaking change on all users. 

It may however be possible to add additional methods to the XeroHttpClient work at the API response level rather than the Accounting/Payroll object list level

**Comment by MJMortimer** [comment]
Closing this as a workaround has been offered. If this still proves to be a nuisance in the future we may look to implement a change
