### ISSUE TITLE
Impossible to disable paging

### ISSUE THREAD

**Issue by davidhusselmann** [XeroAPI/Xero-Net#241]
I had a use case where I needed to disable paging.  This is not possible to do via Xero-Net; you are forced to page through items 100 at a time.  This isn't efficient when trying to retrieve 4,000 contacts from a large Xero organisation (and, while I haven't tested this, it is possible if you create/delete a contact _while_ you are paging, you end up losing/duplicating a record).

Long story short - allow me to turn paging off on a per-endpoint basis, please.

------

**Workaround** for anyone else hitting this:

This extension method uses reflection to remove the `page` parameter from the query string.  It's not pretty and future Xero-Net releases might break this, but it's the best I could do to solve my problem.
```
public static T NoPaging<T>(this T endpoint)
  where T : IPageableEndpoint<T>
{
  endpoint.GetType().GetMethod(
    "RemoveParameter",  System.Reflection.BindingFlags.Instance
               | System.Reflection.BindingFlags.NonPublic)
      .Invoke(endpoint, new[] { "page" });
  return endpoint;
}
```

Sample invocation:

```
xeroCoreApi.Contacts.NoPaging().Find();
```

**Comment by MJMortimer** [comment]
Hey @davidhusselmann,

I'll look into the feasibility of implementing a 'NoPaging' option. Originally the intention was to always enforce paging by default but I understand that this should be able to be overridden if required

**Comment by MJMortimer** [comment]
Hey @davidhusselmann, I'm sorry,  but we will not be looking into supporting non paged requests for endpoints that are paged by default

**Comment by davidhusselmann** [comment]
Understand the decision, but this does not solve the problem of missing a record if something gets inserted on the Xero end while I'm paging through results.

Have you got any comment on that?

**Comment by MJMortimer** [comment]
One workaround you could do is add ordering or filtering. Maybe grab the current time and page through contacts whos last updatedDateUTC was less than that time. It would prevent you from rereading a contact that is updated during your search. 
Of course one may argue that it is better to grab the updated contacts as well because the data is still valid and not stale and instead page through contacts ordered by UpdatedDateUTC. Build up a dictionary of contactIds -> contacts, so that you only ever have the most up to date list of contacts when your job ends.

**Comment by davidhusselmann** [comment]
The problem is not re-reading a contact if one has been updated, the problem is missing another unrelated record.

Here is a simple example; let's assume the page size is 5, not 100.

1. Contacts in Xero: `1 2 3 4 5 6 7 8 9` (in order of UpdatedDateUTC)
2. I request page 1, so I get back `1 2 3 4 5`
3. Now a user updates contact 3.  Data in Xero becomes `1 2 4 5 6 7 8 9 3`.
4. I request page 2, and get back `7 8 9 3`, missing out on contact 6.

There is no way for me to guarantee that I'm getting ALL the records if I'm using paging, because the underlying data keeps changing.  This is a big deal for us as we rely on having an exact copy of the data in our database.  Missing out on an invoice could cost our clients real money.

**Comment by MJMortimer** [comment]
Yep, I can definitely see a problem with that. From what I can tell, there is no 'easy' way around that at the moment. Will need to talk with other devs and see what we can do. I can't promise a time frame however

**Comment by MatthewSteeples** [comment]
How about ordering them in a descending manner (newest first)

1. Contacts in Xero: `9 8 7 6 5 4 3 2 1`
2. You request page 1, so get back `9 8 7 6 5`. Make a note of the timestamp of `1`
3. User updates `4`, so data becomes `4 9 8 7 6 5 3 2 1`
4. You request page 2, and get back `5 3 2 1`
5. Either because you've detected a duplicate, or just as a precaution, you then request pages again from 1 onwards until you hit an updated date that is less than the one you made a note of in step 2

**Comment by davidhusselmann** [comment]
@MJMortimer thank you, that would be greatly appreciated.  I've got a workaround for now, but an "official" way in the API would be much better for future proofing.

@MatthewSteeples thanks for the suggestion.  I guess it is workable, but you have to agree it's a bit of a roundabout way to get a dataset from an API.
