### ISSUE TITLE
Any know issues with batch updates with LinkedTransactions

### ISSUE THREAD

**Issue by andycwk** [XeroAPI/Xero-Net#249]
Hay,

So I'm trying to perform a batch update of linked transactions to save a few api calls... but I'm only seeing the first item being updated in the Xero draft invoice!

My logging shows that I am indeed passing multiple entries into the update command... is there anything else I need to do apart from calling api.LinkedTransactions.Update(<<list>>)

Or is this something I need to raise with Xero support?

Cheers guys!

**Comment by MJMortimer** [comment]
I've just reproduced this, and using Fiddler I can see that it's the API itself not returing more than the first LinkedTransaction. You will need to raise this with the Xero support team.

**Comment by MJMortimer** [comment]
I've just taken a look and it's intentional that LinkedTransactions are single operation endpoints. The SDK just allows you to pass in a list of linkedtransactions due to it's inheritance of the IXeroUpdateEndpoint interface.

You will want to only use the Create and update methods that use singular Linktransaction arguments

**Comment by andycwk** [comment]
Great!

I didn't notice that limitation in the the Xero API docs :/

Anyway.. I've raised an issue with Xero support and will take up the discussion with them as it could be quite expensive attaching a bunch of billable expenses in an invoice without the batch capability.

I'll respond back on this issue once they provide an answer :)

Thanks for your time... it's really appreciated!
