### ISSUE TITLE
Get reports concurrently

### ISSUE THREAD

**Issue by antonberezan** [XeroAPI/Xero-Net#252]
When I'm trying to get two o more reports concurrently I receive an error. In case of PL it's "Message=Report Parameter fromDate could not be parsed as a DateTime". It happens because [XeroReadEnpoint clears query string only after the data has fetched](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Common/XeroReadEndpoint.cs#L179). Why can't you clear it before the request? It'll allow to make concurrent requests.

**Comment by MJMortimer** [comment]
Hey @antonberezan.

Can you please open a pull request with your desired change and then we can look closely at what knock on effects a change like that may cause.

**Comment by MJMortimer** [comment]
Hey @antonberezan, is this something you are still pursuing and able to add via a pull request?

**Comment by antonberezan** [comment]
Hi @MJMortimer, no I'm not.

**Comment by MJMortimer** [comment]
This functionality will probably not be added into this repository due to the probably breaking changes it would require in the inner workings of the clients. I have however solved this issue in the new dotnet standard version of the SDK found [here](https://github.com/XeroAPI/Xero-NetStandard) by reworking the client and endpoint architecture making the endpoints immutable
