### ISSUE TITLE
Adding Files

### ISSUE THREAD

**Issue by prozak91** [XeroAPI/Xero-Net#281]
I am trying to upload a pdf file to xero (see code snippet below)  but keep getting a bad request

                File xerofile = new File();
                xerofile.FileName = path + "\\" + fileName;
                xerofile.Name = fileName;
                xerofile.Mimetype = "application/pdf";
                xerofile.FolderId = xeroConn.Inbox.InboxFolder.Id;
                System.IO.StreamReader sourceStream = new System.IO.StreamReader(xerofile.FileName);
                byte[] fileContents = Encoding.UTF8.GetBytes(sourceStream.ReadToEnd());
                sourceStream.Close();
                xeroConn.Files.Add(xerofile.FolderId, xerofile,fileContents);

I have tried different encoding methods for the file contents ( ASCII encoding and also no encoding just calling File.ReadAllBytes() ) 

also when Calling Folders.Find() returns a SerializationExeption error message below:

	System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'FolderResponse', got string starting with: [{"Name":"Inbox","FileCount":2,"Email":"xero.inbox
	   at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(Type type, String strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
	   at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
	   at Xero.Api.Infrastructure.Http.XeroHttpClient.Read[TResult,TResponse](Response response)
	   at Xero.Api.Common.XeroReadEndpoint`3.Get(String endpoint, String child)
	   at papercutScanUpload.Program.Main(String[] args) in C:\Users\Public\Documents\Zak\PaytecProjects\paytec_exporter2.0\papercutScanUpload\papercutScanUpload\Program.cs:line 41

Apologizes if I am using the API incorrectly

**Comment by fmtrance** [comment]
I have also been experiencing both of the same issues. 

The bad request appears to be caused because of the MimeType. A work aroud for me, was to either remove the MimeType of the Xero File object or change it to "application/octet-stream". Either options worked for me when using File.ReadAllBytes() to get the file content.

`var bytes = System.IO.File.ReadAllBytes(file.FullName);

                var xeroFile = new Xero.Api.Core.Model.File
                {
                    Content = bytes,
                    CreatedDateUtc = DateTime.UtcNow,
                    FileName = file.Name,
                    FolderId = folder.Id,
                    Mimetype = "application/octet-stream",
                    Name = file.Name,
                    Size = bytes.Length
                };

                this.Api().Files.Add(folder.Id, xeroFile, bytes);`

For the Folder.Find() exception, I only need to find a specific folder so I tried to get around this by including a query string.

` var folders = this.Api().Folders.Where($"Name==\"{folderName}\"").Find(); 
`
For some reason, this still returned all of the folders rather than filtering (I'm not sure if my query string is incorrect) but this successfully gave me the list of folders in Xero at least.

**Comment by nishankc** [comment]
Can anyone confirm if adding a file works? I have tried both the above methods but I am continually getting a bad request. I am able to get files fine, just not able to add any.

**Comment by MJMortimer** [comment]
There are [examples for how to use the add files here](https://github.com/XeroAPI/Xero-Net/tree/master/CoreTests/Integration/Files)

I'm going to close this issue due to a lack of movement. Please reopen/open a new issue if required
