### ISSUE TITLE
No Credit Note LineItemId

### ISSUE THREAD

**Issue by crazyhor77** [XeroAPI/Xero-Net#353]
When creating invoices I am storing the lineitemid's in case I need to update them later.  I was also trying to do this with Credit Notes, but I have noticed the LineItemId's for credit note line items are empty.

I have also noticed when using the xero previewer, no lineitemid's are returned for credit note line items.

Is this by design or is it a bug?

**Comment by MJMortimer** [comment]
This was initially by design. The reason we included LineItemID on invoices was so you could link the invoices lineitem when creating Linked Transactions (Billable Expenses).

If you'd like to see LineItemIDs returned on credit notes, I'd suggest voting for it on our [uservoice page](https://xero.uservoice.com/)
