### ISSUE TITLE
SalesTaxBasis is not populated correctly.

### ISSUE THREAD

**Issue by mattliuoz** [XeroAPI/Xero-Net#377]
SalesTaxBasis is always "None" even when an organisation has the value of "CASH" for example.

**Comment by MatthewSteeples** [comment]
We found the same thing and it's done in our fork but haven't pushed for merging it in because there's a few breaking changes. We can verify that the fix looks good though!

https://github.com/MatthewSteeples/Xero-Net/commit/7cdda4d13a67606eafea1071a7c5620b270d115e#diff-aa07f430d9df422635c9bcdc2a26cab4

**Comment by mattliuoz** [comment]
thanks @MatthewSteeples I am taking a different approach to make it less broken and Just updated my PR

**Comment by MJMortimer** [comment]
Added in latest merge. New version will be going out shortly
