### ISSUE TITLE
Send email after saveAll method?

### ISSUE THREAD

**Issue by gleighfield** [XeroAPI/Xero-Net#395]
Is it possible via the API to not only save all my invoices being made with one API call but to tell it to email them also? 

I'm creating 100+ invoices once a month, and hitting into API limits currently, would be great to have one call to not only create them (currently working just fine) but to email them also!

Maybe something like the below?

`$xero->saveAll($invoices)->sendEmail();`

Many thanks,

**Comment by MJMortimer** [comment]
Hey @gleighfield,

This functionality doesn't currently exist in the Xero API and so this sounds like an issue with the Xero API rather than this SDK. If you;d like to try and get this on our roadmap, then please raise on our [User Voice page](https://xero.uservoice.com/forums/5528-xero-accounting-api)
