### ISSUE TITLE
Implement new Quotes API

### ISSUE THREAD

**Issue by scottcurrie** [XeroAPI/Xero-Net#417]
If this work isn't already underway and nearly complete, our company can implement it and create a PR this week. My only concern is that there are a large number of PRs that appear to be sitting without much commentary or review. Is that going to happen to our PR as well, if we do this work for the project?

**Comment by MatthewSteeples** [comment]
Hi @scottcurrie 

Non-Xero employee here. We have forked this library and are maintaining that [here](https://github.com/matthewsteeples/Xero-Net) currently. Our NuGet packages are currently published in a private feed, but if it would be beneficial we'd consider opening that up so that others can take advantage of it. We'd be happy to integrate your pull request into our fork of it.

**Comment by SidneyAllen** [comment]
Thanks for chiming in @MatthewSteeples.

The README for this project says ...

"We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base."

I think collaborating with Matthew and other is a good solution as OAuth 1.0a is slated for deprecation we are focusing our energies on OAuth 2.0 SDKs.

**Comment by MJMortimer** [comment]
@SidneyAllen is correct. We won't be adding new features like this to this SDK. Apologies for the obvious inconvenience
